In [2]:
# Just Import the libraries for data analysis and visualization
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set visualization style
sns.set_theme(style="whitegrid")

In [3]:
# Now we are just loading the dataset
df = pd.read_csv("Transaction_risk_insights.csv")

In [4]:
df.head(10)

,transaction_id,customer_id,transaction_date,transaction_time,account_type,transaction_type,transaction_amount,transaction_direction,account_balance,merchant_category,state,credit_score,has_loan,loan_type,emi_amount,transaction_status,channel,kyc_status,is_fraud,transaction_hour
0,TXN000000001,CUST015796,2019-01-01,15:28,Current,UPI,1820.17,Debit,609365.31,Food & Dining,Maharashtra,764,0,NaN,0.00,Success,Branch,Verified,0,15
1,TXN000000002,CUST000861,2019-01-01,03:00,Current,UPI,392.67,Credit,14451.14,Education,West Bengal,630,0,NaN,0.00,Success,Mobile_App,Verified,0,3
2,TXN000000003,CUST076821,2019-01-01,18:03,Fixed Deposit,POS,1255.97,Debit,47621.87,Utilities,Punjab,813,1,Home,1433.91,Success,Mobile_App,Verified,0,18
3,TXN000000004,CUST054887,2019-01-01,08:03,Savings,UPI,2580.68,Debit,34467.85,Travel,Karnataka,628,1,Personal,6280.35,Success,API,Verified,0,8
4,TXN000000005,CUST006266,2019-01-01,14:23,Fixed Deposit,UPI,2573.80,Debit,26617.40,Utilities,West Bengal,767,0,NaN,0.00,Success,API,Verified,0,14
5,TXN000000006,CUST037195,2019-01-01,01:51,Fixed Deposit,Net_Banking,39172.48,Debit,1798.86,Government,Karnataka,707,1,Auto,4197.37,Pending,Web,Verified,0,1
6,TXN000000007,CUST044132,2019-01-01,06:27,Savings,NEFT,4008.09,Credit,177668.37,Investment,Punjab,361,1,Home,4251.79,Success,ATM,Verified,0,6
7,TXN000000008,CUST060264,2019-01-01,23:40,Current,Net_Banking,17797.85,Debit,17568.23,Healthcare,Punjab,651,0,NaN,0.00,Success,Mobile_App,Expired,0,23
8,TXN000000009,CUST016024,2019-01-01,20:25,Salary,Credit_Card,3284.62,Debit,66973.00,Food & Dining,Tamil Nadu,443,0,NaN,0.00,Success,Web,Verified,0,20
9,TXN000000010,CUST041091,2019-01-01,22:15,Savings,Net_Banking,921.64,Debit,36054.94,Real Estate,Karnataka,330,1,Personal,9630.13,Success,Web,Verified,0,22

In [5]:
# Now we will see the dimensions of the dataset
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 550000
Number of columns: 20

In [6]:

# Just generating statistical summary of the dataset
df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
transaction_id,550000,550000,TXN000000001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_id,550000,79916,CUST003688,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transaction_date,550000,1827,2023-11-11,373,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transaction_time,550000,1440,06:25,448,NaN,NaN,NaN,NaN,NaN,NaN,NaN
account_type,550000,5,Savings,219651,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transaction_type,550000,10,UPI,153986,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transaction_amount,550000.0,NaN,NaN,NaN,29907.093934,139610.09652,2.4,763.0375,2035.735,8557.4975,10000000.0
transaction_direction,550000,2,Debit,370394,NaN,NaN,NaN,NaN,NaN,NaN,NaN
account_balance,550000.0,NaN,NaN,NaN,84550.115076,170914.586239,500.0,15157.785,36422.87,87607.035,5000000.0
merchant_category,550000,15,Retail,66180,NaN,NaN,NaN,NaN,NaN,NaN,NaN
state,550000,10,Maharashtra,98911,NaN,NaN,NaN,NaN,NaN,NaN,NaN
credit_score,550000.0,NaN,NaN,NaN,599.807009,173.054597,300.0,450.0,600.0,750.0,899.0
has_loan,550000.0,NaN,NaN,NaN,0.349615,0.476849,0.0,0.0,0.0,1.0,1.0
loan_type,172866,6,Personal,47810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
emi_amount,550000.0,NaN,NaN,NaN,2365.859974,4973.54608,0.0,0.0,0.0,3115.03,153325.74
transaction_status,550000,4,Success,506247,NaN,NaN,NaN,NaN,NaN,NaN,NaN
channel,550000,6,Mobile_App,208368,NaN,NaN,NaN,NaN,NaN,NaN,NaN
kyc_status,550000,3,Verified,483457,NaN,NaN,NaN,NaN,NaN,NaN,NaN
is_fraud,550000.0,NaN,NaN,NaN,0.00886,0.09371,0.0,0.0,0.0,0.0,1.0
transaction_hour,550000.0,NaN,NaN,NaN,11.504431,6.924499,0.0,6.0,11.0,17.0,23.0


#### Important Observations.

- **Dataset size:** This Dataset has 550,000 transactions and 20 columns.
- **Unique transactions:** All 550,000 transaction have unique IDs .
- **Customers:** 79,916 unique customers have multiple transactions.
- **Transaction amount:** Average transaction amount is ₹29,907.09, and maximum transection amount is ₹1 crore.
- **Missing values:** The `loan_type` column has many missing values so we need to fix it.
- **Fraud rate:** Approximately 0.886% of transactions are labeled as fraud.
- **Transaction time:** The `transaction_hour` column ranges from 0 to 23, which will allow us for hourly pattern analysis.

#### `1:-` Now we will check missing values, duplicate records, duplicate transaction IDs, and the distribution of fraud labels before cleaning the dataset.

In [7]:
# just Checking for missing values
print("Missing Values:")
display(df.isnull().sum().sort_values(ascending=False))

Missing Values:

loan_type                377134
transaction_id                0
customer_id                   0
is_fraud                      0
kyc_status                    0
channel                       0
transaction_status            0
emi_amount                    0
has_loan                      0
credit_score                  0
state                         0
merchant_category             0
account_balance               0
transaction_direction         0
transaction_amount            0
transaction_type              0
account_type                  0
transaction_time              0
transaction_date              0
transaction_hour              0
dtype: int64

In [8]:
# Now we are just Checking for duplicate rows
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [9]:
# Now we are checking for duplicate transaction IDs
print("Duplicate Transaction IDs:",
      df["transaction_id"].duplicated().sum())

Duplicate Transaction IDs: 0

In [10]:
# Now we are just checking fraud distribution
print("\nFraud Label Counts:")
print(df["is_fraud"].value_counts())

Fraud Label Counts:
is_fraud
0    545127
1      4873
Name: count, dtype: int64

In [14]:
# Now we are just checking fraud percentages
print("\nFraud Label Percentages:")
print((df["is_fraud"].value_counts(normalize=True) * 100).round(2))

Fraud Label Percentages:
is_fraud
0    99.11
1     0.89
Name: proportion, dtype: float64


#### Important Observations.
-  The `loan_type` column contains 377,134 missing values. Other columns have no missing values.
-  There are no duplicate rows in our dataset.
-  There are No duplicate transaction IDs in our dataset.

#### `2:-`Now we will Handle the Missing Values

In [13]:
# Before we handle the missing values lets see if the missing values coming from the  customers who do not have a loan.
pd.crosstab(
    df["has_loan"],
    df["loan_type"].isnull(),
    margins=True
)

loan_type   False    True     All
has_loan
0               0  357712  357712
1          172866   19422  192288
All        172866  377134  550000



#### Important Observations.
- we found that 357,712 records have no loan type mentioned (which generally means that they dosenot have a lone).
- But we found that  19,422 records out of 357,712 records have a lone which is mention in `has_loan` column but in  the `loan_type` column we found that it has no lone (means these are missing value).
- Now we can say that there are 19,422 missing values in the `lone_type`column

In [46]:
# Now we are just verifying if the column has_loan has genuine values or not .
# and to do that we are checking the emi_amount column so that we can verify if they have an active emi which can confrom that they genually have a loan or not.
df[
    (df["has_loan"] == 1) &
    (df["loan_type"].isnull()) &
    (df["emi_amount"] > 0)
][["customer_id", "has_loan", "loan_type", "emi_amount"]].sample(10)

       customer_id  has_loan loan_type  emi_amount
546646  CUST008251         1       NaN    11523.20
436367  CUST055686         1       NaN     3847.71
274287  CUST062835         1       NaN    10074.32
342389  CUST041204         1       NaN     2619.04
81218   CUST045794         1       NaN     5144.92
398255  CUST059505         1       NaN     8231.28
207943  CUST078003         1       NaN     9161.39
424088  CUST070580         1       NaN     3567.65
140032  CUST023974         1       NaN     1877.19
100656  CUST044496         1       NaN     7797.48

In [47]:
# Now we are creating an new category for the missing values which has a loan but the loan type is missinng
df_clean = df.copy()

df_clean.loc[
    (df_clean["has_loan"] == 1) &
    (df_clean["loan_type"].isnull()),
    "loan_type"
] = "Loan Type Unknown"

print(df_clean["loan_type"].value_counts())

loan_type
Personal             47810
Home                 38252
Auto                 29219
Business             28863
Loan Type Unknown    19422
Education            19074
Gold                  9648
Name: count, dtype: int64

In [49]:
# now we are creating an new category for the missing values which dosenot have an loan
df_clean.loc[
    (df_clean["has_loan"] == 0) &
    (df_clean["loan_type"].isnull()),
    "loan_type"
] = "No Loan"
print(df_clean["loan_type"].value_counts())

loan_type
No Loan              357712
Personal              47810
Home                  38252
Auto                  29219
Business              28863
Loan Type Unknown     19422
Education             19074
Gold                   9648
Name: count, dtype: int64

In [53]:
# just checking is all the missing values are gone or not
df_clean.isnull().sum()

transaction_id           0
customer_id              0
transaction_date         0
transaction_time         0
account_type             0
transaction_type         0
transaction_amount       0
transaction_direction    0
account_balance          0
merchant_category        0
state                    0
credit_score             0
has_loan                 0
loan_type                0
emi_amount               0
transaction_status       0
channel                  0
kyc_status               0
is_fraud                 0
transaction_hour         0
dtype: int64


#### Important Observation
- We replaced missing loan types for customers without a loan with `No Loan`.
- and we replaced missing loan types for customers with a loan with `Loan Type Unknown`.
- so that we can Preserve all transaction records without deleting any rows.

#### `3:-`Now we will check the data typs and convert them in correct format

In [54]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550000 entries, 0 to 549999
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   transaction_id         550000 non-null  object
 1   customer_id            550000 non-null  object
 2   transaction_date       550000 non-null  object
 3   transaction_time       550000 non-null  object
 4   account_type           550000 non-null  object
 5   transaction_type       550000 non-null  object
 6   transaction_amount     550000 non-null  float64
 7   transaction_direction  550000 non-null  object
 8   account_balance        550000 non-null  float64
 9   merchant_category      550000 non-null  object
 10  state                  550000 non-null  object
 11  credit_score           550000 non-null  int64
 12  has_loan               550000 non-null  int64
 13  loan_type              550000 non-null  object
 14  emi_amount             550000 non-null  float64
 15  transaction_status     550000 non-null  object
 16  channel                550000 non-null  object
 17  kyc_status             550000 non-null  object
 18  is_fraud               550000 non-null  int64
 19  transaction_hour       550000 non-null  int64
dtypes: float64(3), int64(4), object(13)
memory usage: 83.9+ MB


### Important Observations
- `transaction_date` column is stored as object and we need to convert it to a date format.
- `transaction_time` is also stored as text so we need to change that to.
- Transaction amounts, account balances, and EMI amounts are already in numeric format.
- The `has_loan` and `is_fraud` columns are stored as integers.

In [ ]:
# now we will convert the transaction_date from object to datetime format
df_clean["transaction_date"] = pd.to_datetime(
    df_clean["transaction_date"],
    errors="coerce"
)

In [61]:
# now we will convert the  transaction_time from objectto a proper time format
df_clean["transaction_time"] = pd.to_datetime(
    df_clean["transaction_time"],
    format="%H:%M",
    errors="coerce"
)

In [60]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550000 entries, 0 to 549999
Data columns (total 20 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   transaction_id         550000 non-null  object
 1   customer_id            550000 non-null  object
 2   transaction_date       550000 non-null  datetime64[ns]
 3   transaction_time       0 non-null       datetime64[ns]
 4   account_type           550000 non-null  object
 5   transaction_type       550000 non-null  object
 6   transaction_amount     550000 non-null  float64
 7   transaction_direction  550000 non-null  object
 8   account_balance        550000 non-null  float64
 9   merchant_category      550000 non-null  object
 10  state                  550000 non-null  object
 11  credit_score           550000 non-null  int64
 12  has_loan               550000 non-null  int64
 13  loan_type              550000 non-null  object
 14  emi_amount             550000 non-null  float64
 15  transaction_status     550000 non-null  object
 16  channel                550000 non-null  object
 17  kyc_status             550000 non-null  object
 18  is_fraud               550000 non-null  int64
 19  transaction_hour       550000 non-null  int64
dtypes: datetime64[ns](2), float64(3), int64(4), object(11)
memory usage: 83.9+ MB